# Generated by Django 4.1.5 on 2023-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("descriotion", models.CharField(max_length=250)),
                ("in_list", models.BooleanField(default=True)),
                ("created", models.TimeField(auto_now=True)),
                ("finished", models.TimeField(default=True)),
            ],
        ),
    ]
