# Generated by Django 4.1.5 on 2023-01-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_descriotion_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="finished",
            field=models.DateTimeField(default=True),
        ),
    ]
