# Generated by Django 4.1.5 on 2023-01-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_remove_task_created_remove_task_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(default="...", max_length=250),
        ),
    ]
