# Generated by Django 4.1.5 on 2023-02-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="in_archive",
            field=models.BooleanField(default=False),
        ),
    ]
