# Generated by Django 4.1.5 on 2023-02-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0008_task_in_archive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="in_archive",
        ),
    ]
