# Generated by Django 4.1.5 on 2023-02-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0009_remove_task_in_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
